### ISSUE TITLE
Does this overlap with sly-package-inferred?

### ISSUE THREAD

**Issue by Ambrevar** [mmgeorge/sly-asdf#10]
From the readme:
```
Ported from slime with changes to support package-inferred-system. 
```

Does this mean that this contrib overlaps with
https://github.com/40ants/sly-package-inferred ?

**Comment by mmgeorge** [comment]
@Ambrevar I think that contrib is for improving sly autocompletion when used with package-inferred-system. This contrib does not do anything to autocompeletion, instead the changes I made were to allow functions that work on systems to also work for `package-inferred-system` (e.g. browse-system, search-system, save-system, etc).

What this contrib (and slime-asdf) does is basically give you several utility commands for working with systems as well as better integrates system loading with sly (i.e., so that you get system compilation errors as you would with other sly compilation errors rather than getting dumped into the debugger as you would with calling asdf:load-system directly). Still some issues where certain asdf errors are not caught and reported properly which I'm currently working on.

**Comment by mmgeorge** [comment]
Also currently in the process of adding flycheck-like support that loads systems to check for compilation errors in a separate process.

**Comment by Ambrevar** [comment]
Great, thanks for the details!
What about adding this to the readme?
